#!/bin/bash

#INFO: Aggiunge tutti i file rilevati da git status, gestendo rename, untracked e modifiche. Commit e push automatici.

cd /Users/adriano/WORK/sviluppo/prep_center

function ex {
	echo -e "\nERRORE: il $1 non si e' completato correttamente\n"
	exit 1
}

commit_msg="$1"

# Ricava la lista di file
files_to_add=$(git status --porcelain | cut -c4- | grep -v -e swo -e swp | cut -f1,3 -d" " | tr '\n' ' ')
if [[ -z "$(echo "$files_to_add" | tr -d '[:space:]')" ]]; then
  echo "Nessun file da aggiungere."
  exit 0
fi

echo
echo git add "$files_to_add"
git add $files_to_add || ex "comando add"

# Controllo modifiche effettive
if git diff --cached --quiet; then
  echo "Nessuna modifica da committare dopo l'add. Uscita."
  exit 0
fi

# Commit e push
# Chiede il messaggio se non fornito
if [[ -z "$commit_msg" ]]; then
  read -rp "Inserisci il messaggio del commit (invio per lasciarlo vuoto): " commit_msg
fi

echo git commit -m "$commit_msg"
git commit -m "$commit_msg" || ex commit
echo git push
git push || ex push
echo 

exit:
