[deploy]
postDeployCommand = "cd backend && echo 'Creating migrations...' && python manage.py makemigrations && echo 'Applying migrations...' && python manage.py migrate && echo 'Migrations completed'" 