# Generated by Django 4.2.16 on 2024-09-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField()),
                ('box_type', models.CharField(max_length=255)),
                ('picked', models.DateField(blank=True, null=True)),
                ('shipped', models.DateField(blank=True, null=True)),
                ('lpn', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('additional_info', models.CharField(blank=True, max_length=255, null=True)),
                ('other_info', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(max_length=255)),
                ('verification_request', models.BooleanField(default=False)),
                ('verification_question', models.TextField(blank=True, null=True)),
                ('verification_response', models.TextField(blank=True, null=True)),
                ('asin', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('fnsku', models.CharField(max_length=255)),
                ('ean', models.CharField(blank=True, max_length=13, null=True)),
                ('product_code', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('state_amz', models.CharField(max_length=255)),
                ('reason_amz', models.CharField(max_length=255)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('company', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
