# Generated by Django 4.2.16 on 2025-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0005_outgoingmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id_api', models.CharField(help_text='ID API della spedizione', max_length=50)),
                ('shipment_name', models.CharField(help_text='Nome della spedizione', max_length=255)),
                ('shipment_type', models.CharField(help_text='Tipo di spedizione (inbound/outbound)', max_length=20)),
                ('product_title', models.TextField(blank=True, help_text='Titolo/Nome del prodotto', null=True)),
                ('product_sku', models.CharField(blank=True, help_text='SKU del prodotto', max_length=255, null=True)),
                ('product_asin', models.CharField(blank=True, help_text='ASIN del prodotto', max_length=50, null=True)),
                ('product_fnsku', models.CharField(blank=True, help_text='FNSKU del prodotto', max_length=50, null=True)),
                ('product_quantity', models.IntegerField(blank=True, help_text='Quantità del prodotto nella spedizione', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risultato Ricerca Item',
                'verbose_name_plural': 'Risultati Ricerca Items',
                'ordering': ['shipment_name', 'product_title'],
            },
        ),
    ]
