# Generated by Django 4.2.16 on 2025-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0006_searchresultitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultitem',
            name='processing_status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], default='complete', max_length=20),
        ),
        migrations.AddField(
            model_name='searchresultitem',
            name='search_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='product_asin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='product_fnsku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='product_sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='product_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='shipment_id_api',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='shipment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchresultitem',
            name='shipment_type',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
