# Generated by Django 4.2.13 on 2025-06-13 08:12

from django.db import migrations, models

def remove_duplicate_webhooks(apps, schema_editor):
    """
    Rimuove i duplicati dalla tabella ShipmentStatusUpdate prima di aggiungere
    il vincolo di unicità.
    """
    ShipmentStatusUpdate = apps.get_model('prep_management', 'ShipmentStatusUpdate')
    db_alias = schema_editor.connection.alias
    
    # Query per trovare i duplicati
    duplicates = ShipmentStatusUpdate.objects.using(db_alias).values(
        'shipment_id', 'event_type', 'new_status', 'merchant_id'
    ).annotate(
        count=models.Count('id')
    ).filter(count__gt=1)
    
    # Per ogni gruppo di duplicati, mantieni solo il record più recente
    for dup in duplicates:
        # Prendi tutti i record duplicati ordinati per created_at (decrescente)
        records = ShipmentStatusUpdate.objects.using(db_alias).filter(
            shipment_id=dup['shipment_id'],
            event_type=dup['event_type'],
            new_status=dup['new_status'],
            merchant_id=dup['merchant_id']
        ).order_by('-created_at')
        
        # Mantieni il primo (più recente) ed elimina gli altri
        first = records.first()
        if first:
            records.exclude(id=first.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0016_alter_outgoingmessage_message_id_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_webhooks),
    ]
