# Generated by Django 4.2.13 on 2025-06-13 17:37

from django.db import migrations

def truncate_all_tables(apps, schema_editor):
    """
    Svuota completamente tutte le tabelle per ripartire da zero.
    Questo approccio è radicale ma definitivo:
    1. Svuota la tabella ShipmentStatusUpdate
    2. Svuota la tabella TelegramNotification
    3. Rimuove tutti i dati precedenti
    """
    db_alias = schema_editor.connection.alias
    
    # 1. Svuota la tabella ShipmentStatusUpdate
    truncate_shipment_updates = """
    TRUNCATE TABLE prep_management_shipmentstatusupdate RESTART IDENTITY CASCADE;
    """
    
    # 2. Svuota la tabella TelegramNotification
    truncate_telegram_notifications = """
    TRUNCATE TABLE prep_management_telegramnotification RESTART IDENTITY CASCADE;
    """
    
    # Esegui le query
    schema_editor.execute(truncate_shipment_updates)
    schema_editor.execute(truncate_telegram_notifications)

class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0017_handle_duplicate_webhooks'),
    ]

    operations = [
        migrations.RunPython(truncate_all_tables),
    ]
