# Generated by Django 4.2.13 on 2025-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0018_remove_duplicate_webhooks'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shipmentstatusupdate',
            constraint=models.UniqueConstraint(
                fields=('shipment_id', 'event_type', 'new_status', 'merchant_id'),
                name='unique_webhook_per_shipment_event'
            ),
        ),
    ]
