# Generated by Django 4.2.13 on 2025-06-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0019_add_webhook_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipmentstatusupdate',
            name='unique_webhook_per_shipment_event',
        ),
    ]
