# Generated by Django 4.2.13 on 2025-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0022_force_remove_all_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSPAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome identificativo per questa configurazione', max_length=100, unique=True, verbose_name='Nome configurazione')),
                ('refresh_token', models.CharField(help_text="Token di refresh ottenuto durante l'autorizzazione", max_length=500, verbose_name='Refresh Token')),
                ('lwa_app_id', models.CharField(help_text="ID dell'applicazione Login with Amazon", max_length=255, verbose_name='LWA App ID')),
                ('lwa_client_secret', models.CharField(help_text="Secret dell'applicazione Login with Amazon", max_length=255, verbose_name='LWA Client Secret')),
                ('marketplace', models.CharField(choices=[('IT', 'Amazon.it (Italia)'), ('DE', 'Amazon.de (Germania)'), ('FR', 'Amazon.fr (Francia)'), ('ES', 'Amazon.es (Spagna)'), ('GB', 'Amazon.co.uk (Regno Unito)'), ('US', 'Amazon.com (Stati Uniti)')], default='IT', help_text='Marketplace Amazon di riferimento', max_length=2, verbose_name='Marketplace')),
                ('api_timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout API (secondi)')),
                ('max_retries', models.PositiveIntegerField(default=3, verbose_name='Tentativi massimi')),
                ('is_active', models.BooleanField(default=True, help_text='Se attivo, questa configurazione può essere usata', verbose_name='Attivo')),
                ('is_sandbox', models.BooleanField(default=False, help_text="Se True, usa l'ambiente sandbox di Amazon", verbose_name='Sandbox')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo aggiornamento')),
                ('last_test_at', models.DateTimeField(blank=True, help_text='Ultima volta che la connessione è stata testata', null=True, verbose_name='Ultimo test')),
                ('last_test_success', models.BooleanField(blank=True, null=True, verbose_name='Ultimo test riuscito')),
                ('last_test_message', models.TextField(blank=True, null=True, verbose_name='Messaggio ultimo test')),
                ('total_api_calls', models.PositiveIntegerField(default=0, verbose_name='Chiamate API totali')),
                ('total_api_errors', models.PositiveIntegerField(default=0, verbose_name='Errori API totali')),
            ],
            options={
                'verbose_name': 'Configurazione Amazon SP-API',
                'verbose_name_plural': 'Configurazioni Amazon SP-API',
                'ordering': ['marketplace', 'name'],
            },
        ),
    ]
