# Generated by Django 4.2.13 on 2025-06-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0023_add_amazon_sp_api_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonspapiconfig',
            name='aws_access_key',
            field=models.CharField(blank=True, help_text='Access Key ID del tuo IAM User AWS', max_length=255, null=True, verbose_name='AWS Access Key ID'),
        ),
        migrations.AddField(
            model_name='amazonspapiconfig',
            name='aws_secret_key',
            field=models.CharField(blank=True, help_text='Secret Access Key del tuo IAM User AWS', max_length=255, null=True, verbose_name='AWS Secret Access Key'),
        ),
        migrations.AddField(
            model_name='amazonspapiconfig',
            name='role_arn',
            field=models.CharField(blank=True, help_text="ARN del ruolo IAM per l'accesso alle SP-API (es: arn:aws:iam::123456789:role/SellingPartnerAPIRole)", max_length=255, null=True, verbose_name='AWS IAM Role ARN'),
        ),
    ]
