# Generated by Django 4.2.13 on 2025-07-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep_management', '0024_add_aws_credentials_to_spapi_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonspapiconfig',
            name='marketplace_id',
            field=models.CharField(blank=True, help_text='ID specifico del marketplace Amazon (es: APJ6JRA9NG5V4 per Amazon.it)', max_length=20, null=True, verbose_name='Marketplace ID'),
        ),
    ]
