# Generated by Django 4.2.13 on 2025-06-13 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pallet_label', '0003_add_lingua_etichette'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='palletlabel',
            new_name='pallet_labe_created_7c5367_idx',
            old_name='pallet_labe_created_aa2b08_idx',
        ),
        migrations.RenameIndex(
            model_name='palletlabel',
            new_name='pallet_labe_numero__f5c68a_idx',
            old_name='pallet_labe_numero__7a4829_idx',
        ),
        migrations.RenameIndex(
            model_name='palletlabel',
            new_name='pallet_labe_nome_ve_322a09_idx',
            old_name='pallet_labe_nome_ve_ad8b91_idx',
        ),
    ]
