# Generated by Django 4.2.16 on 2024-10-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('return_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreturn',
            name='product_code',
        ),
        migrations.AddField(
            model_name='productreturn',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
